import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/containers/Navbar";
import { Inter } from 'next/font/google'
import Banner from "@/components/containers/Banner";
 
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "YorkBooking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-x-hidden flex-col h-full items-center`}
      >
        <Navbar />
        <Banner />
        {children}
      </body>
    </html>
  );
}
